[
  {
    id: 'id-1',
    name: 'Шевцов Єгор',
    role: 'Project Manager',
    link: 'https://www.linkedin.com/in/yehor-shevtsov/',
    img: '',
  },
  {
    id: 'id-2',
    name: 'Юрій Шукан',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/yuriy-shukan/',
    img: '',
  },
  {
    id: 'id-3',
    name: 'Дуднік Анна',
    role: 'Front-end розробник',
    link: 'http://www.linkedin.com/in/anna-dudnik-dev/',
    img: '',
  },
  {
    id: 'id-4',
    name: 'Ратушняк Ілона',
    role: 'UI/UX Designer ',
    link: 'http://linkedin.com/in/ilona-ratushniak-3a678624b/',
    img: '',
  },
  {
    id: 'id-5',
    name: 'Анна Ричкова',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/annarychkova1/',
    img: '',
  },
  {
    id: 'id-6',
    name: 'Дудка Анастасія',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/anastasiia-dudka-/',
    img: '',
  },
  {
    id: 'id-7',
    name: 'Демчук Володимир',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/demchuk-volodymyr/',
    img: '',
  },
  {
    id: 'id-8',
    name: 'Савченко Сергій',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/serhiy-savchenko/',
    img: '',
  },
  {
    id: 'id-9',
    name: 'Кудлай Микита',
    role: 'Front-end розробник',
    link: 'https://www.linkedin.com/in/mykytakudlai/',
    img: '',
  },
  {
    id: 'id-10',
    name: 'Кароліна Таран',
    role: 'Front-end розробник',
    link: 'http://www.linkedin.com/in/karolina-taran-developer/',
    img: '',
  },
  {
    id: 'id-11',
    name: 'Сергій Монжелесов',
    role: 'Front-end розробник',
    link: 'http://www.linkedin.com/in/serhii-monzhelesov/',
    img: '',
  },
  {
    id: 'id-12',
    name: 'Людмила Пасєка',
    role: 'QA-тестувальник',
    link: 'https://www.linkedin.com/in/liudmyla-pasieka-112a6429b/',
    img: '',
  },
  {
    id: 'id-13',
    name: 'Олена Салобай',
    role: 'QA-тестувальник',
    link: 'http://www.linkedin.com/in/olena-salobai/',
    img: '',
  },
  {
    id: 'id-14',
    name: 'Сенчишин Любомир',
    role: 'QA-тестувальник',
    link: 'https://www.linkedin.com/in/liubomyr-senchyshyn-691596298/',
    img: '',
  },
  {
    id: 'id-15',
    name: 'Анна Олійник',
    role: 'QA-тестувальник',
    link: 'https://www.linkedin.com/in/hanna-oliinyk-66835715a/',
    img: '',
  },
  {
    id: 'id-16',
    name: 'Нікіта Яцухно',
    role: 'QA-тестувальник',
    link: 'http://www.linkedin.com/in/nikita-yatsukhno/',
    img: '',
  },
];
